name: dart_sampler
description: A Dart library for random sampling from strings, lists, maps, and iterators using pluggable distributions. 
version: 1.0.0
repository: https://github.com/IvoSchols/dart_sampler

environment:
  sdk: ^3.7.2

dependencies:
  # no external dependencies

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

export:
  - 'lib/sample.dart'